In [69]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Load the CSV file into a pandas dataframe
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1dFdlvgmyXfN3SriVn5Byv_BNtyroICxdgrQKBzuMA1U/export?format=csv&id=1dFdlvgmyXfN3SriVn5Byv_BNtyroICxdgrQKBzuMA1U&gid=0")


# Split the data into training and testing sets
train_data, test_data, train_labels, test_labels = train_test_split(df['message'], df['sentiment'], test_size=0.2)

# Preprocess the labels by encoding them as integer values
encoder = LabelEncoder()
train_labels = encoder.fit_transform(train_labels)
test_labels = encoder.transform(test_labels)

# Tokenize the messages using the TensorFlow Tokenizer
#tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=1000)
new_train_data=[]
#clean data
for d in train_data:
  d=str(d)
  new_train_data.append(d)

new_test_data=[]
for d in test_data:
  d=str(d)
  new_test_data.append(d)

# Tokenize the messages using the TensorFlow Tokenizer
tokenizer.fit_on_texts(new_train_data)
train_data = tokenizer.texts_to_matrix(new_train_data)
test_data = tokenizer.texts_to_matrix(new_test_data)

#Define the neural network model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(1000,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(8, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
print(train_data, train_labels)
history = model.fit(train_data, train_labels, epochs=10, validation_data=(test_data, test_labels))

# Evaluate the model on the test data
test_loss, test_acc = model.evaluate(test_data, test_labels)
print('Test accuracy:', test_acc)







[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]] [1 1 5 ... 5 1 5]
Epoch 1/10
4710/4710 [==============================] - 24s 5ms/step - loss: 1.2924 - accuracy: 0.4771 - val_loss: 1.2578 - val_accuracy: 0.4924
Epoch 2/10
4710/4710 [==============================] - 19s 4ms/step - loss: 1.2254 - accuracy: 0.5066 - val_loss: 1.2497 - val_accuracy: 0.4977
Epoch 3/10
4710/4710 [==============================] - 19s 4ms/step - loss: 1.1883 - accuracy: 0.5240 - val_loss: 1.2580 - val_accuracy: 0.4957
Epoch 4/10
4710/4710 [==============================] - 17s 4ms/step - loss: 1.1537 - accuracy: 0.5406 - val_loss: 1.2670 - val_accuracy: 0.4930
Epoch 5/10
4710/4710 [==============================] - 18s 4ms/step - loss: 1.1217 - accuracy: 0.5555 - val_loss: 1.2878 - val_accuracy: 0.4928
Epoch 6/10
4710/4710 [==============================] - 19s 4ms/step - loss: 1.0946 - accuracy: 0.569

In [70]:
helper = {1:"Curious to dive deeper", 
          6:"Sad",
          7:"Surprised",
          5:"Neutral",
          4:"Happy",
          3:"Fearful",
          0:"Angry"}

In [71]:
#Example test
random_str = "Which I find surprising since the US seems to prefer american football more."

In [74]:
results = helper[np.argmax(model.predict(tokenizer.texts_to_matrix([random_str])))]

1/1 [==============================] - 0s 28ms/step


In [75]:
print(results)

Neutral
